# Load and explore the data

## Import libraries

In [1]:
# Import pandas, numpy, and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# seaborn is a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

## Load the data

##### Load the Seattle data set

In [2]:
df_seattle = pd.read_csv('/Users/williamdang/Documents/Weather/Data/seattle_rain.csv')

##### Load the Portland, Maine data set

In [3]:
df_portland = pd.read_csv('/Users/williamdang/Documents/Weather/Data/portland_maine_rain.csv')

## Explore the contents of the data sets

##### Start by looking at the head of each data frame.

This will let us see the names of the columns and a few example values for each column.

In [4]:
df_seattle.head()
df_portland.head()

       STATION                NAME        DATE  DAPR  MDPR  PRCP  SNOW  SNWD
0  USC00174782  LONG ISLAND, ME US  2018-01-01   NaN   NaN  0.00   0.0   NaN
1  USC00174782  LONG ISLAND, ME US  2018-01-02   NaN   NaN  0.00   0.0   NaN
2  USC00174782  LONG ISLAND, ME US  2018-01-03   NaN   NaN  0.00   0.0   NaN
3  USC00174782  LONG ISLAND, ME US  2018-01-04   NaN   NaN  0.00   0.0   NaN
4  USC00174782  LONG ISLAND, ME US  2018-01-05   NaN   NaN  0.62   9.0   NaN

##### Examine more rows

In [5]:
df_seattle.head(15)

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,WESD,WESF
0,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/1/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
1,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/2/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/3/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
3,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/4/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/5/18,NaN,NaN,0.25,NaN,NaN,NaN,NaN
5,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/6/18,NaN,NaN,0.57,NaN,NaN,NaN,NaN
6,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/7/18,NaN,NaN,0.23,NaN,NaN,NaN,NaN
7,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/8/18,NaN,NaN,0.41,NaN,NaN,NaN,NaN
8,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/12/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
9,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/13/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
10,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/14/18,NaN,NaN,0.20,NaN,NaN,NaN,NaN
11,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/15/18,NaN,NaN,0.02,NaN,NaN,NaN,NaN
12,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/16/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
13,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/17/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
14,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",3/18/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN

##### Portland, ME data set

In [6]:
df_portland.head(15)

        STATION                NAME        DATE  DAPR  MDPR  PRCP  SNOW  SNWD
0   USC00174782  LONG ISLAND, ME US  2018-01-01   NaN   NaN  0.00   0.0   NaN
1   USC00174782  LONG ISLAND, ME US  2018-01-02   NaN   NaN  0.00   0.0   NaN
2   USC00174782  LONG ISLAND, ME US  2018-01-03   NaN   NaN  0.00   0.0   NaN
3   USC00174782  LONG ISLAND, ME US  2018-01-04   NaN   NaN  0.00   0.0   NaN
4   USC00174782  LONG ISLAND, ME US  2018-01-05   NaN   NaN  0.62   9.0   NaN
5   USC00174782  LONG ISLAND, ME US  2018-01-06   NaN   NaN  1.00  13.0   NaN
6   USC00174782  LONG ISLAND, ME US  2018-01-07   NaN   NaN  0.01   0.5   NaN
7   USC00174782  LONG ISLAND, ME US  2018-01-08   NaN   NaN  0.00   0.0   NaN
8   USC00174782  LONG ISLAND, ME US  2018-01-09   NaN   NaN  0.00   0.0   NaN
9   USC00174782  LONG ISLAND, ME US  2018-01-10   NaN   NaN  0.00   0.0   NaN
10  USC00174782  LONG ISLAND, ME US  2018-01-11   NaN   NaN  0.00   0.0   NaN
11  USC00174782  LONG ISLAND, ME US  2018-01-12   NaN   NaN  0.00   0.0   NaN
12  USC00174782  LONG ISLAND, ME US  2018-01-13   NaN   NaN  1.04   0.0   NaN
13  USC00174782  LONG ISLAND, ME US  2018-01-14   NaN   NaN  0.00   0.0   NaN
14  USC00174782  LONG ISLAND, ME US  2018-01-15   NaN   NaN  0.00   0.0   NaN

##### Are the columns are the same?

In [7]:
print(df_seattle.columns.tolist())
print(df_portland.columns.tolist())

# columns in Seattle that are not in Portland
print('Only in Seattle:', df_seattle.columns.difference(df_portland.columns).tolist())

['STATION', 'NAME', 'DATE', 'DAPR', 'MDPR', 'PRCP', 'SNOW', 'SNWD', 'WESD', 'WESF']
['STATION', 'NAME', 'DATE', 'DAPR', 'MDPR', 'PRCP', 'SNOW', 'SNWD']
Only in Seattle: ['WESD', 'WESF']

##### Use the `info` method to check the data types, size of the data frame, and numbers of missing values.

In [8]:
df_seattle.info()

<class 'pandas.DataFrame'>
RangeIndex: 1658 entries, 0 to 1657
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  1658 non-null   str
 1   NAME     1658 non-null   str
 2   DATE     1658 non-null   str
 3   DAPR     23 non-null     float64
 4   MDPR     23 non-null     float64
 5   PRCP     1636 non-null   float64
 6   SNOW     353 non-null    float64
 7   SNWD     66 non-null     float64
 8   WESD     15 non-null     float64
 9   WESF     28 non-null     float64
dtypes: float64(7), str(3)
memory usage: 194.4 KB

##### Portland, ME data set

In [9]:
df_portland.info()

<class 'pandas.DataFrame'>
RangeIndex: 20780 entries, 0 to 20779
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  20780 non-null  str
 1   NAME     20780 non-null  str
 2   DATE     20780 non-null  str
 3   DAPR     478 non-null    float64
 4   MDPR     466 non-null    float64
 5   PRCP     20228 non-null  float64
 6   SNOW     14307 non-null  float64
 7   SNWD     7933 non-null   float64
dtypes: float64(5), str(3)
memory usage: 2.1 MB

##### We can also compare data frame sizes using the shape attribute

In [10]:
print('Seattle: ', df_seattle.shape)
print('Portland:', df_portland.shape)

Seattle:  (1658, 10)
Portland: (20780, 8)

## Why might the St. Louis data set be larger?


The Portland, Maine file contains readings from **29 different weather stations** around the Portland area, each with its own row for every day, while the Seattle file comes from a single station. It also covers all of 2018–2022 for many stations.

#### Examine the `STATION` column

##### How many unique stations are present?

#### Examine the `DATE` column

### Be careful to use correct data types

### Convert `DATE` to datetime

### What range of dates are present?

### Are the data suitable for answering the question?

Plot the daily precipitation data for Seattle.

##### Plot the daily precipitation data for St. Louis.

## Tutorial: Selecting subsets of a DataFrame

In [11]:
df_seattle.head()

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,WESD,WESF
0,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/1/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
1,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/2/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/3/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
3,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/4/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/5/18,NaN,NaN,0.25,NaN,NaN,NaN,NaN

### Select one column

Select the column containing precipitation `PRCP`.

#### Use dictionary-style indexing

#### Use explicit array-style indexing with loc

#### Use implicit array-style indexing with `.iloc`

What number column, starting with 0, is `PRCP`?

In [12]:
df_seattle.head()

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,WESD,WESF
0,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/1/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
1,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/2/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/3/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
3,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/4/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/5/18,NaN,NaN,0.25,NaN,NaN,NaN,NaN

##### Use implicit array-style indexing with `.iloc`

### Select multiple columns

Select the columns containing `STATION`, `DATE`, and precipitation `PRCP`.

##### Use .loc

##### Use .iloc

#### Select a range of columns

Select all columns from `STATION` through `PRCP`

##### Use .iloc

### Select the first $n$ rows

Select the first 3 rows

Use the `.head()` method

##### Use explicit indexing

##### Use implicit indexing

### Select the last $n$ rows

Use the `.tail()` method

##### Use explicit indexing

##### Use implicit indexing

### Select rows using logical indexing

Select the rows where `PRCP` is greater than 0.

##### Select the rows where the precipitation is between 0.5 and 0.75 inches.

## Select relevant subsets of the data

We saw that the St. Louis data set contains data prior to 2018.

In [13]:
df_stlouis.head()

NameError: name 'df_stlouis' is not defined

##### Limit the St. Louis data to 2018 and beyond.

##### The St. Louis data set has values for many weather stations, while the Seattle data set has only one weather station.

We will focus on the data from the airport in St. Louis.

## Join data frames keeping `DATE` and `PRCP` columns

In [ ]:
df_seattle.head(2)

In [ ]:
df_stlouis.head(2)

**What type of join should we do?**

##### Use a join to keep all dates present

Each DataFrame had a column named `PRCP`, so the default is to add suffixes _x and _y to differentiate the columns. Normally, I would rename the columns at this point to something more informative. However, I know that I want to convert the DataFrame to a tidy format and I will modify the names later.

### Create a tidy data frame with columns for city and precipitation

In [ ]:
df

How did this change the DataFrame?

In [ ]:
df.head()

### Rename columns or values to follow best practices

Rename the city values 'STL' and 'SEA'

##### Rename the columns to be lowercase using `df.rename()`

## Identify and fill in missing values

Data can be missing in multiple manners:
1. Values are `NaN` in the data frame

2.  Values are not included in the data set.

### Count the non-null or null values

Determine the number of non-null values in each column.

##### Determine the number of null values in each column.

##### Determine the number of null precipitation values for Seattle and St. Louis.

##### The St. Louis data set does not have any `NaN` values of `precipitation`. Are any dates omitted?

**How many data points should we have from 2018 to 2022?**

### Impute missing values

We will replace missing values with the mean across years of values on that day.


**Design an algorithm for replacing missing values with the mean across years of values on that day.**

## Export the clean .csv file

In [ ]:
df.to_csv('clean_seattle_stlouis_weather.csv', encoding='utf-8-sig', index=False)